### ISSUE TITLE
Defaulting to no swap on EL8

### ISSUE THREAD

**Issue by Klaas-** [openlogic/AzureBuildCentOS#104]
Hi,
it seems with the change to CentOS8 you dropped the default creation of swap space. Is that on purpose?

If the answer is "yes we do not create swap on purpose" then as a follow up -- what is the suggested way of creating swap space for el8?
Via WALinuxAgent or via  temp-disk-swapfile.service & /usr/local/sbin/temp-disk-swapfile

It is present in the el7 kickstarts that use cloud init:
https://github.com/openlogic/AzureBuildCentOS/blob/master/ks/azure/centos79-LVM.ks#L354-L431

In the el8 kickstarts it is referenced in the in the cloud init configuration, but not actually created.
https://github.com/openlogic/AzureBuildCentOS/blob/master/ks/azure/centos83-LVM.ks#L367

As a personal opinion, I would default to creating swap space.

Greetings
Klaas

**Comment by N3WWN** [comment]
Hi @Klaas- !

Yes, that is correct:  We dropped the default creation of swap for CentOS 8 images.

We did retain the creation of swap on CentOS 7 images after changing the provisioning from WALinuxAgent to cloud-init so that instances behave the same within the major version.

There have been provisioning changes recently, though, and swap creation on cloud-init provisioned VMs will be disabled on CentOS 7 images when they are refreshed (probably later this month).  The reason for this is that WALinuxAgent no longer creates swap for instances that are not cloud-init provisioned.

To address how best to create swap for el8:
With the image refresh, I'm going to try to include the `temp-disk-swapfile.service` file in the CentOS 8 images, but it will remain disabled.  You would only need to enable it to create the swap.

I understand the opinion to have swap enabled by default. We went back and forth on whether or not to enable it or disable it, weighing the pros and cons, and in the end we decided to disable it since enabling it (when the end user desired) would be relatively easy.  I believe that behavior aligned with the RHEL 8 images at that time, also.

-Rich

**Comment by Klaas-** [comment]
Hi,
that sounds reasonable.
Is the 2GB size hardcoded at the moment? https://github.com/openlogic/AzureBuildCentOS/blob/master/ks/azure/centos79-LVM.ks#L406
maybe put it into a seperate line, config file or even an env variable so it's easily overwritten via systemd drop in file?

**Comment by N3WWN** [comment]
Yes, the 2GB limit is currently hardcoded.  

I don't know for sure, but was likely to ensure that the swapfile would fit within every ephemeral disk size at that time.  

What if, like you suggested, there was a file `/etc/sysconfig/swapfile` that could contain `SWAPFILESIZE=<size in MB>`?

If that file is missing, it would default to the current value of 2048?

```
--- temp-disk-swapfile.orig	2020-10-08 15:26:10.365465858 +0000
+++ temp-disk-swapfile	2021-01-20 22:23:52.369267426 +0000
@@ -23,9 +23,10 @@ start() {
     fi
 
     SWAPFILEPATH="${MOUNTPATH}/swapfile"
+    [ -z "$SWAPFILESIZE" ] && SWAPFILESIZE=2048
 
     if [ ! -f "$SWAPFILEPATH" ]; then
-        (sh -c 'rm -f "$1" && umask 0066 && { fallocate -l "${2}M" "$1" || dd if=/dev/zero "of=$1" bs=1M "count=$2"; } && mkswap "$1" || { r=$?; rm -f "$1"; exit $r; }' 'setup_swap' "$SWAPFILEPATH" '2048') || (echo "Failed to create swapfile at $SWAPFILEPATH"; exit 1)
+        (sh -c 'rm -f "$1" && umask 0066 && { fallocate -l "${2}M" "$1" || dd if=/dev/zero "of=$1" bs=1M "count=$2"; } && mkswap "$1" || { r=$?; rm -f "$1"; exit $r; }' 'setup_swap' "$SWAPFILEPATH" "$SWAPFILESIZE") || (echo "Failed to create swapfile at $SWAPFILEPATH"; exit 1)
         echo "Successfully created swapfile at $SWAPFILEPATH"
     fi
     swapon "$SWAPFILEPATH" || (echo "Failed to activate swapfile at $SWAPFILEPATH"; exit 1)
```

If that's usable, I'll present it to my contacts at Microsoft to see if we can get it approved.

-Rich

**Comment by Klaas-** [comment]
Hi,
yes, something along those lines, if you put it into /etc/sysconfig/swapfile you will need to reference it in the unit file of the service like:
```
[Service]
EnvironmentFile=-/etc/sysconfig/swapfile
```

What I had in mind was something along the lines of this: with the changes to temp-disk-swapfile the default service would remain the same. If you want to increase swap you would do something like:
```
$ cat >> /etc/systemd/system/temp-disk-swapfile.service.d/override.conf <<EOF
[Service]
Environment="SWAPFILESIZE=4096"
EOF
$ systemctl daemon-reload
$ systemctl start temp-disk-swapfile.service
```

But a file in sysconfig seems equally valid to me.

Greetings
Klaas

**Comment by Klaas-** [comment]
At the end of the day, I would like this to be solved the same way for rhel and centos aswell, these differences will make using the same ansible code harder :D

**Comment by Klaas-** [comment]
Microsoft Support suggest to use cloudinit for rhel rather than a service. This would be sufficient solution for me on centos as well.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cloudinit-configure-swapfile

**Comment by N3WWN** [comment]
Hi @Klaas- !

Sorry for skipping past the addition of `EnvironmentFile` to the service.  I had that on my test VM, just forgot to mention it.

Based on Microsoft Support's response, it seems that there's nothing for me to do.

That being the case, I'll close this issue as resolved.

Thanks!

-Rich

**Comment by Klaas-** [comment]
@N3WWN yeah you should just clean the references to the non-existent service https://github.com/openlogic/AzureBuildCentOS/blob/master/ks/azure/centos83-LVM.ks#L367 for example

**Comment by N3WWN** [comment]
True ;)  I'll discuss how Microsoft wants to clean that up (remove the reference or include the service file).
