### ISSUE TITLE
sudo (CVE-2021-3156) patch missing on OpenLogic CentOS7 repo

### ISSUE THREAD

**Issue by dongfu-nu** [openlogic/AzureBuildCentOS#109]
Hello OL CentOS Repo (olcentgbl.trafficmanager.net) admins,

Please sync or add sudo-1.8.23-10.el7_9.1.x86_64.rpm to the OL CentOS repo so Azure OpenLogic based VMs can remediate the latest sudo vulnerability.

OL-CentOS:
http://olcentgbl.trafficmanager.net/centos/7.9.2009/updates/x86_64/?C=M;O=D

CentOS Mirror:
http://mirror.centos.org/centos/7/updates/x86_64/Packages/?C=M;O=D

sudo-devel-1.8.23-10.el7_9.1.i686.rpm | 2021-01-26 22:59 | 51K 
sudo-devel-1.8.23-10.el7_9.1.x86_64.rpm | 2021-01-26 22:59 | 51K |  
sudo-1.8.23-10.el7_9.1.x86_64.rpm | 2021-01-26 22:59 | 843K |  

Thanks.

**Comment by N3WWN** [comment]
Thanks for bringing this to our attention!

There was an issue with sync'ing some of the latest CentOS 7.9 packages after Jan 25, 2021.  We were able to isolate the problem and resolved it this morning.

At this point, all of our repos have sync'd after the fix was pushed and the updated sudo packages are now present.
