### ISSUE TITLE
Questions about CentOS-HPC and kernel handling

### ISSUE THREAD

**Issue by Klaas-** [openlogic/AzureBuildCentOS#43]
Hi,
https://github.com/szarkos/AzureBuildCentOS/blob/master/ks/azure/centos74-hpc.ks#L163
handles that kernel packages will never bee updated on a HPC server. This seems to be from the requirements of the rdma packages: microsoft-hyper-v-rdma // kmod-microsoft-hyper-v-rdma.

My questions:
* is that really what you want? :) Theses machines will not pop up in the Update management ie all kernel security issues are ignored in azure monitoring
* does it really make sense to put rpms into other rpms instead of putting them into the repository? (http://olcentgbl.trafficmanager.net/openlogic/7/openlogic/x86_64/RPMS/msft-rdma-drivers-4.2.3.1-20180209.x86_64.rpm includes the rdma drivers rpms)
* how do you recommend to update those machines? :)

**Comment by szarkos** [comment]
Hi Klaas,

> is that really what you want?

Yes, it is intentional as the version of the LIS and network-direct driver that's installed for HPC is tightly bundled with the kernel.

> does it really make sense to put rpms into other rpms instead of putting them into the repository? 

A bit of a long story, but this is by design with our current HPC implementation.  One aspect is that by bundling the RPMs for all the various CentOS versions into a single RPM, it reduces the complexity of the Linux agent when it needs to download and update the drivers.  It also reduces confusion as the bundled RPMs for HPC are similar to, but different than the standard LIS drivers :/

Another aspect is that the network-direct driver that provides access to the infiniband controller on the guest must match the version that is installed on the Host side.  The version is passed via KVP from the host to the guest, read by the Azure agent, and then the agent decides which driver to load.  Thus more complexity we prefer to hide and let the agent deal with.

> how do you recommend to update those machines?

From our experience we've found that many HPC customers tend to have versions of their applications that are certified for a particular version of CentOS anyway, and tend to customize and capture a known stable version of their image rather than upgrade in place.

Yet if needed you can update pretty much any package you want, but upgrading the kernel takes some care to avoid breaking your cluster, so we lock that to avoid folks completely breaking a cluster.

Looking to the future I hope we can provide direct access to the IB controller via our PCI passthrough driver.  This driver didn't exist when we devised the mechanism that we use currently.  I don't have an ETA for this, but when it comes it will certainly reduce the complexity described above and allow for more seamless upgrades.

Thanks,
Steve

**Comment by Klaas-** [comment]
So for me that would mean:
- I have to use my own tools to monitor vulnerabilities for the HPC machines because update manager can't work with excluded packages
- Rather than update the kernel version I'll recreate the VMs when a new image becomes available -- means I have to monitor that somehow

Side note:
I think the dependencies of your rpm packages are wrong or you should put them into a different directory
```
rpm -ql kmod-microsoft-hyper-v-rdma-4.2.3.1.144-20180209.x86_64
/etc/depmod.d/hyperv.conf
/lib/modules/3.10.0-693.17.1.el7.x86_64
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hid-hyperv.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_balloon.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_netvsc.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_network_direct.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_sock.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_storvsc.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_utils.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hv_vmbus.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hyperv-keyboard.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/hyperv_fb.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/pci-hyperv.ko
/lib/modules/3.10.0-693.17.1.el7.x86_64/extra/microsoft-hyper-v-rdma/uio_hv_generic.ko
# rpm -qR kmod-microsoft-hyper-v-rdma-4.2.3.1.144-20180209.x86_64
/usr/sbin/depmod
/usr/sbin/depmod
kernel >= 3.10.0-693
kernel < 3.10.0-694
```
I think the dependency should be kernel = 3.10.0-693.17.1.el7 or put into dir /lib/modules/3.10.0-693.el7.x86_64
